### ISSUE TITLE
info about the XML source

### ISSUE THREAD

**Issue by arademaker** [bond-lab/omw-data#7]
Can we have any additional information about how this XML file was produced? 

https://github.com/bond-lab/omw-data/blob/9f2df85bbbab39370e265a2e2d90d95b6d015f04/wns/pwn30/README#L4

**Comment by fcbond** [comment]
@jmccrae Can you let us know a bit more about how this was made?

If there is some documentation, I will link to it, ...

**Comment by goodmami** [comment]
@arademaker I'm not certain, but I think that file was created with the [gwn-scala-api](https://github.com/jmccrae/gwn-scala-api) converter. This issue was closed when Francis merged my pull request which added the code we'll use to create a new conversion and also the following page to explain the usage of the code: https://github.com/bond-lab/omw-data/tree/main/scripts

I hope that is sufficient.
